version: "3.7"

services:
  server:
    init: true
    image: headscale/headscale:v0.28.0
    restart: on-failure
    stop_grace_period: 1m
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/config:/etc/headscale:rw
    environment:
      - TZ=${TZ:-UTC}
      - HEADSCALE_CONFIG=/etc/headscale/config.yaml
    env_file:
      - ${APP_DATA_DIR}/config/config.env
    labels:
      yantr.app: "madutxo-headscale"
      yantr.service: "Headscale Server"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3